// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4d_Ph_kV4zyHlrnUEwwxWG-OR7Twebhw',
    appId: '1:791781374835:android:3838362fc5727b1061e306',
    messagingSenderId: '791781374835',
    projectId: 'robust-caldron-428902-r5',
    storageBucket: 'robust-caldron-428902-r5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0GuvmPrMDMEAI7-HAE3PgzWdvwWk4oqs',
    appId: '1:791781374835:ios:1c00ba77efdaae4061e306',
    messagingSenderId: '791781374835',
    projectId: 'robust-caldron-428902-r5',
    storageBucket: 'robust-caldron-428902-r5.appspot.com',
    iosBundleId: 'com.assistid.privata',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0GuvmPrMDMEAI7-HAE3PgzWdvwWk4oqs',
    appId: '1:791781374835:ios:f1a819e5b6ea4a9861e306',
    messagingSenderId: '791781374835',
    projectId: 'robust-caldron-428902-r5',
    storageBucket: 'robust-caldron-428902-r5.appspot.com',
    iosBundleId: 'com.assistid.privata.privata',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB862gMexEYPdQXbVzlVplAPWJQ39ONSSc',
    appId: '1:791781374835:web:0dae2bc93bbc693c61e306',
    messagingSenderId: '791781374835',
    projectId: 'robust-caldron-428902-r5',
    authDomain: 'robust-caldron-428902-r5.firebaseapp.com',
    storageBucket: 'robust-caldron-428902-r5.appspot.com',
    measurementId: 'G-6G4LNHWB5G',
  );

}